spring:
  application:
    name: blog-backend

  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: abc123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: YourSecretKeyForJWTTokenGenerationMustBeLongEnoughForHS256Algorithm
  expiration: 86400000 # 24 hours in milliseconds

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:5173}

notion:
  token: ${NOTION_TOKEN:}
  version: ${NOTION_VERSION:2025-09-03}
  publicImportEnabled: ${NOTION_PUBLIC_IMPORT_ENABLED:false}
  oauth:
    client-id: ${NOTION_OAUTH_CLIENT_ID:}
    client-secret: ${NOTION_OAUTH_CLIENT_SECRET:}
    redirect-uri: ${NOTION_OAUTH_REDIRECT_URI:}
    success-redirect: ${NOTION_OAUTH_SUCCESS_REDIRECT:/admin/upload}
